
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 07 13:38:04 BOT 2024
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Else_If = 7;
  public static final int OP_MenorOIgual = 21;
  public static final int If = 5;
  public static final int ParentesisAbierto = 12;
  public static final int Else = 6;
  public static final int Start = 30;
  public static final int Error = 35;
  public static final int LlaveCerrado = 15;
  public static final int OP_NoIgual = 22;
  public static final int While = 9;
  public static final int Division = 28;
  public static final int NumeroDecimal = 31;
  public static final int Int = 2;
  public static final int Cadena = 34;
  public static final int Float = 3;
  public static final int Modulo = 29;
  public static final int OP_Igualdad = 17;
  public static final int For = 8;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Linea = 11;
  public static final int Imprimir = 10;
  public static final int OP_Menor = 19;
  public static final int LlaveAbierto = 14;
  public static final int OP_Mayor = 18;
  public static final int Exponenciacion = 27;
  public static final int String = 4;
  public static final int Identificador = 32;
  public static final int Resta = 25;
  public static final int ParentesisCerrado = 13;
  public static final int Multiplicacion = 26;
  public static final int OP_MayorOIgual = 20;
  public static final int Numero = 33;
  public static final int Arreglo = 16;
  public static final int Suma = 24;
  public static final int Igual = 23;
}

